[database]
DB_URL = "postgresql://postgres.rejgkwnnndhatvzzvljw:P3nnysupM1ll!319@aws-1-us-east-1.pooler.supabase.com:5432/postgres"

[gemini]
GEMINI_API_KEY = "AIzaSyB9kOfEZ9iG79nmI17QYhVE3HunxCMZW-M"